### PR TITLE
Add Cancancan enrollment supervision status

### PR DESCRIPTION
**Pull request by ManhLeDuc**
## Related Tickets
- [#41407](https://edu-redmine.sun-asterisk.vn/issues/41407)

## WHAT (optional)
- Phân quyền cho các model Enrollment, Supervision, Status

## HOW
- Sử dụng gem cancancan

## Evidence (Screenshot or Video)

### CODE REVIEW

**Comment by trannguyen61** [comment]
OK

**Comment by nguyenquanganhc** [comment]
OK

**Comment by ManhLeDuc** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
