### PR TITLE
#41666/Fix view

### PR DESCRIPTION
**Pull request by trannguyen61**
## Related Tickets
- [#41666](https://edu-redmine.sun-asterisk.vn/issues/41666)

## WHAT (optional)
- Sửa view.

## Evidence (Screenshot or Video)
image

### CODE REVIEW

**Comment by nguyenquanganhc** [comment]
OK

**Comment by ManhLeDuc** [comment]
OK

**Comment by trannguyen61** [comment]
ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
